"""empty message

Revision ID: 7b74f4f37a0e
Revises: None
Create Date: 2016-09-01 23:11:43.882299

"""

# revision identifiers, used by Alembic.
revision = '7b74f4f37a0e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('karma_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_id', sa.String(length=256), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('downvotes', sa.Integer(), nullable=True),
    sa.Column('karma', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('karma_model')
    ### end Alembic commands ###
